version: "3.8"
services:
    postgres:
      image: postgres
      container_name: postgres
      environment:
        POSTGRES_DB: password_keeper
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
      ports:
        - "5432:5432"
      volumes:
        - ./pgdata:/var/lib/postgres/data