version: "3.8"
services:
    db:
      image: postgres
      container_name: postgres
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: password_keeper
      ports:
        - "5432:5432"
      volumes:
        - ./pgdata:/var/lib/postgres/data
